language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 8.0
    - php: nightly

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction --prefer-dist

script:
  - Swop\GitHubWebHook\Tests\Security\SignatureValidatorTest --coverage-text
