name: tests
on: [push, pull_request]
jobs:
  tests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.2', '7.3', '7.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/phpunit --coverage-text --verbose